dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('individual-registration', views.IndividualRegistrationView.as_view(),name='individual-registration'),
    path('individual-detail/<int:pk>/', views.IndividualDetailView.as_view(),name='individual-detail'),
    path('individual-detail/update/<int:pk>/', views.IndividualUpdateView.as_view(),name='individual-detail-update'),
    path('individual-registrations', views.IndividualRegistrations.as_view(),name='individual-registrations'),
    path('registration-success', views.RegistrationSuccessView.as_view(),name='registration-success'),
    path('corporate-registration', views.CorporateRegistrationView.as_view(),name='corporate-registration'),
    path('corporate-registrations', views.CorporateRegistrations.as_view(),name='corporate-registrations'),
    path('corporate-detail/<int:pk>/', views.CorporateDetailView.as_view(),name='corporate-detail'),
    path('corporate-detail/update/<int:pk>/', views.CorporateUpdateView.as_view(),name='corporate-detail-update'),
    path('tax-office-create', views.TaxOfficeCreateView.as_view(),name='tax-office-create'),
    path('tax-office-update/<int:pk>/', views.TaxOfficeUpdateView.as_view(),name='tax-office-update'),
    path('tax-office-detail/<int:pk>/', views.TaxOfficeDetailView.as_view(),name='tax-office-detail'),
    path('tax-offices', views.TaxOfficeListView.as_view(),name='tax-offices'),
    path('subsidiary-registration', views.SubsidiaryRegistrationView.as_view(),name='subsidiary-registration'),
    path('subsidiary-registrations', views.SubsidiaryRegistrations.as_view(),name='subsidiary-registrations'),
    path('subsidiary-detail/<int:pk>/', views.SubsidiaryDetailView.as_view(),name='subsidiary-detail'),
    path('subsidiary-detail/update/<int:pk>/', views.SubsidiaryUpdateView.as_view(),name='subsidiary-detail-update'),
    path('individual-shareholder-create/<int:pk>', views.IndividualShareholderCreateView.as_view(),name='individual-shareholder-create'),
    path('corporate-shareholder-create/<int:pk>', views.CorporateShareholderCreateView.as_view(),name='corporate-shareholder-create'),
    path('individual-taxpayer-report', views.IndividualTaxPayerReport.as_view(),name='individual-taxpayer-report'),
    path('individual-taxpayer-report-view/<int:tax_office>/<start_date>/<end_date>/', views.IndividualTaxPayerReportView.as_view(),name='individual-taxpayer-report-view'),
    path('corporate-taxpayer-report', views.CorporateTaxPayerReport.as_view(),name='corporate-taxpayer-report'),
    path('corporate-taxpayer-report-view/<int:tax_office>/<start_date>/<end_date>/', views.CorporateTaxPayerReportView.as_view(),name='corporate-taxpayer-report-view'),
    path('biometric-capture/<int:pk>', views.BiometricCreateView.as_view(),name='biometric-capture'),
    path('bvn-initiate-data', views.BVNInitiateData.as_view(),name='bvn-initiate-data'),
    path('bvn-request-data', views.BVNRequestData.as_view(),name='bvn-request-data'),
    path('bvn-list-data', views.BVNListData.as_view(),name='bvn-list-data'),
    path('bvn-detail-data/<int:pk>/', views.BVNDetailData.as_view(),name='bvn-detail-data'),
    path('bvn-generate-tin', views.BVNGenerateTIN.as_view(),name='bvn-generate-tin'),
]

jtbapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework import routers
from api import views

# api URLs
router = routers.DefaultRouter()
router.register(r'individual', views.IndividualTaxPayerViewset)
router.register(r'corporate', views.CorporateTaxPayerViewset)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', auth_views.LoginView.as_view(template_name='account/login.html'), name='index'),
    path('api/', include(router.urls)),
    path('apis/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (TemplateView, CreateView, ListView, DetailView,
 UpdateView, FormView, View)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from dashboard.models import (IndividualTaxPayer, CorporateTaxPayer, TaxOffice, SubsidiaryTaxPayer,
IndividualShareholder, CorporateShareholder, Biometric, Agency, Bvn, Country, State, Lga)
from dashboard.forms import (IndividualTaxPayerForm, CorporateTaxPayerForm, TaxOfficeForm,
SubsidiaryTaxPayerForm, IndividualShareholderForm, CorporateShareholderForm,
IndividualTaxPayerReportForm, CorporateTaxPayerReportForm, BiometricForm)
from django.urls import reverse, reverse_lazy
import datetime
from django.http import HttpResponse, HttpResponseRedirect, Http404
import requests
from pprint import pprint

# Create your views here.
class StaffMemberMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

class IndexView(LoginRequiredMixin, StaffMemberMixin,TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['individual_count'] = IndividualTaxPayer.objects.count()
        context['corporate_count'] = CorporateTaxPayer.objects.count()
        context['user_count'] = User.objects.count()
        # todays registrations
        today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
        today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
        context['individual_today']= IndividualTaxPayer.objects.filter(create_time__range=(today_min, today_max)).count()
        context['corporate_today']= CorporateTaxPayer.objects.filter(create_time__range=(today_min, today_max)).count()
                
        # recent registrations
        context['individual_registrations'] = IndividualTaxPayer.objects.all().order_by('-create_time')[:5]
        context['corporate_registrations'] = CorporateTaxPayer.objects.all().order_by('-create_time')[:5]
        return context

class IndividualRegistrationView(StaffMemberMixin, CreateView):
    template_name = 'dashboard/individual/individual_form.html'
    model = IndividualTaxPayer
    form_class = IndividualTaxPayerForm
    success_url = '/dashboard/registration-success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        office = self.request.user.profile.office
        context['office'] = office
        return context

    def form_valid(self, form):
        try:
            agency = Agency.objects.get(abbreviation='JTB')
        except Agency.DoesNotExist:
            agency = None

        form.instance.agency = agency
        form.instance.create_user = self.request.user
        return super().form_valid(form)

class IndividualRegistrations(StaffMemberMixin, ListView):
    model = IndividualTaxPayer
    template_name = 'dashboard/individual/individual_registrations.html'
    context_object_name = 'registrations'

class IndividualDetailView(StaffMemberMixin, DetailView):
    model = IndividualTaxPayer
    template_name = 'dashboard/individual/individual_detail.html'
    context_object_name = 'registration'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tax_payer = IndividualTaxPayer.objects.get(id=self.kwargs['pk'])
        try:
            context['biometric'] = Biometric.objects.get(tax_payer=tax_payer)
        except Biometric.DoesNotExist:
            context['biometric'] = None        
        return context

class IndividualUpdateView(StaffMemberMixin, UpdateView):
    template_name = 'dashboard/individual/individual_form.html'
    model = IndividualTaxPayer
    form_class = IndividualTaxPayerForm
    success_url = '/dashboard/registration-success'

    def form_valid(self, form):        
        form.instance.update_user = self.request.user       
        return super().form_valid(form)


class RegistrationSuccessView(TemplateView):
    template_name = 'dashboard/registration_success.html'

class CorporateRegistrationView(StaffMemberMixin, CreateView):
    template_name = 'dashboard/corporate/corporate_form.html'
    model = CorporateTaxPayer
    form_class = CorporateTaxPayerForm
    success_url = '/dashboard/registration-success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        office = self.request.user.profile.office # tax office for the current user
        context['office'] = office
        return context

    def form_valid(self, form):
        try:
            agency = Agency.objects.get(abbreviation='JTB')
        except Agency.DoesNotExist:
            agency = None

        form.instance.agency = agency        
        form.instance.create_user = self.request.user
        form.instance.tax_office = self.request.user.profile.office       
        return super().form_valid(form)

class CorporateRegistrations(StaffMemberMixin, ListView):
    model = CorporateTaxPayer
    template_name = 'dashboard/corporate/corporate_registrations.html'
    context_object_name = 'registrations'

class CorporateDetailView(StaffMemberMixin, DetailView):
    model = CorporateTaxPayer
    template_name = 'dashboard/corporate/corporate_detail.html'
    context_object_name = 'registration'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        company = CorporateTaxPayer.objects.get(id=self.kwargs['pk'])
        context['ind_shareholders'] = IndividualShareholder.objects.filter(company=company)
        context['corp_shareholders'] = CorporateShareholder.objects.filter(company=company)
        return context

class CorporateUpdateView(StaffMemberMixin, UpdateView):
    template_name = 'dashboard/corporate/corporate_form.html'
    model = CorporateTaxPayer
    form_class = CorporateTaxPayerForm
    success_url = '/dashboard/registration-success'

    def form_valid(self, form):        
        form.instance.update_user = self.request.user       
        return super().form_valid(form)

class TaxOfficeListView(StaffMemberMixin, ListView):
    model = TaxOffice
    template_name = 'dashboard/tax_office/tax_offices.html'
    context_object_name = 'offices'

class TaxOfficeCreateView(StaffMemberMixin, CreateView):
    template_name = 'dashboard/tax_office/tax_offices_form.html'
    model = TaxOffice
    form_class = TaxOfficeForm
    success_url = '/dashboard/registration-success'

    def form_valid(self, form):        
        form.instance.create_user = self.request.user       
        return super().form_valid(form)

class TaxOfficeUpdateView(StaffMemberMixin, UpdateView):
    template_name = 'dashboard/tax_office/tax_offices_form.html'
    model = TaxOffice
    form_class = TaxOfficeForm
    success_url = '/dashboard/registration-success'

    def form_valid(self, form):        
        form.instance.update_user = self.request.user       
        return super().form_valid(form)

class TaxOfficeDetailView(StaffMemberMixin, DetailView):
    model = TaxOffice
    template_name = 'dashboard/tax_office/tax_offices_detail.html'
    context_object_name = 'office'

class SubsidiaryRegistrationView(StaffMemberMixin, CreateView):
    template_name = 'dashboard/subsidiary/subsidiary_form.html'
    model = SubsidiaryTaxPayer
    form_class = SubsidiaryTaxPayerForm
    success_url = '/dashboard/registration-success'

class SubsidiaryRegistrations(StaffMemberMixin, ListView):
    model = SubsidiaryTaxPayer
    template_name = 'dashboard/subsidiary/subsidiary_registrations.html'
    context_object_name = 'subsidiaries'

class SubsidiaryDetailView(StaffMemberMixin, DetailView):
    model = SubsidiaryTaxPayer
    template_name = 'dashboard/subsidiary/subsidiary_detail.html'
    context_object_name = 'subsidiary'

class SubsidiaryUpdateView(StaffMemberMixin, UpdateView):
    template_name = 'dashboard/subsidiary/subsidiary_form.html'
    model = SubsidiaryTaxPayer
    form_class = SubsidiaryTaxPayerForm
    success_url = '/dashboard/registration-success'

    def form_valid(self, form):        
        form.instance.update_user = self.request.user       
        return super().form_valid(form)

class IndividualShareholderCreateView(StaffMemberMixin, CreateView):
    template_name = 'dashboard/individual_shareholder/individual_form.html'
    model = IndividualShareholder
    form_class = IndividualShareholderForm
    #success_url = reverse('dashboard:corporate-detail', kwargs={'pk': self.company.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['company'] = CorporateTaxPayer.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):        
        form.instance.create_user = self.request.user       
        return super().form_valid(form)
"""
# Not yet implemented
class IndividualShareholderUpdateView(StaffMemberMixin, UpdateView):
    template_name = 'dashboard/individual_shareholder/individual_form.html'
    model = IndividualShareholder
    form_class = IndividualShareholderForm
    #success_url = '/dashboard/registration-success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['company'] = CorporateTaxPayer.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):        
        form.instance.update_user = self.request.user       
        return super().form_valid(form)

dashboard/templates/dashboard/tax_office/tax_offices.html
{% extends "dashboard/index.html" %}
{% load staticfiles %}
{% block body %}
<h4>Tax offices</h4>
<hr>
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-4">Tax Offices</h5>
          <a href="{% url 'dashboard:tax-office-create' %}" class="btn btn-behance float-right mb-2">Create Tax Office</a>
          <div class="table-responsive">
            {% if offices %}
              <table class="table center-aligned-table">
                <thead>
                  <tr>
                    <th>SN</th>
                    <th>State</th>
                    <th>LGA</th>
                    <th>Office Name</th>
                    <th>Address</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {% for office in offices %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{office.state}}</td>
                      <td>{{office.lga}}</td>
                      <td>{{office.name}}</td>
                      <td>{{office.address}}</td>
                      <td>{{office.status}}</td>
                      <td>
                        <a href="{% url 'dashboard:tax-office-detail' office.pk %}" class="btn btn-outline-success btn-sm">View</a>
                        <a href="{% url 'dashboard:tax-office-update' office.pk %}" class="btn btn-outline-warning btn-sm">Update</a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% else %}
              <p class="alert alert-info">There are no tax offices in the database</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

dashboard/templates/dashboard/tax_office/tax_offices_detail.html
{% extends "dashboard/index.html" %}
{% load staticfiles %}
{% block body %}
  <h4>
    {{office.name | upper}}
  </h4>
  <hr>
  <table class="table table-striped table-primary">
    <tr>
      <th>State</th>
      <td>{{office.state}}</td>
    </tr>
    <tr>
      <th>LGA</th>
      <td>{{office.lga}}</td>
    </tr>
    <tr>
      <th>Office Name</th>
      <td>{{office.name}}</td>
    </tr>
    <tr>
      <th>Office Address</th>
      <td>{{office.address}}</td>
    </tr>
    <tr>
      <th>Status</th>
      <td>{{office.status}}</td>
    </tr>    
  </table>

{% endblock body %}

dashboard/templates/dashboard/tax_office/tax_offices_form.html
{% extends "dashboard/index.html" %}
{% load staticfiles %}
{% block body %}
  <h4>Tax Office Form</h4>
  <hr>
  <form method="post">
    {% csrf_token %}
      <div class="form-group row">
          <div class="col-sm-4">
            <i>State</i>
            {{form.state}}
            <small class="text-danger">{{form.state.errors}}</small>
          </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-4">
            <i>LGA</i>
          {{form.lga}}
          <small class="text-danger">{{form.lga.errors}}</small>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4">
          {{form.name}}
          <small class="text-danger">{{form.name.errors}}</small>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4">
          {{form.address}}
          <small class="text-danger">{{form.address.errors}}</small>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4">
          <i>Status</i>
          {{form.status}}
          <small class="text-danger">{{form.status.errors}}</small>
        </div>
    </div>      
    <div class="form-group row">
    <div class="col-sm-12">
        <input type="submit" class="btn btn-success" value="Submit">
    </div>
    </div>
  </form>
{% endblock body %}